#let cfg = toml("../../tutor.toml")
#let args_list = (
    "Se piove, i raccolti non soffriranno. Quando la pressione atmosferica si abbassa, piove. La pressione atmosferica si abbassa. Quindi, i raccolti non soffriranno.",
    "Se esco in bici riesco ad arrivare prima. Ma se la ruota della bici si buca non arrivo prima. Quindi, o non esco in bici, oppure la ruota non si buca.",
    "Se in tasca ho 5 euro posso comprare due gelati. Ma se la gelateria è chiusa non posso comprarli. Quindi, o non ho 5 euro, oppure la gelateria è aperta.",
    "Se ricompro la macchina, il finanziamento non può superare il 3% di interesse. Ma i finanziamenti attuali sono tutti almeno al 6% di interesse. Mi sa proprio che non ricompro la macchina.",
    "Mario e Giovanna sono vegetariani, quindi nessuno dei due mangerà la salsiccia. Ma se non mangiano la salsiccia, dovranno mangiare tofu al vapore.",
    "Se l'esattore è alla festa, devo sanare il debito o mi cercherà. Se mi riconosce, mi cerca e non sono salvo. Se non vado via dalla festa e indosso gli occhiali da sole, non mi riconosceranno. O mi riconoscono, o sono salvo. Fortunatamente sono salvo.",
    "Un argomento che ha un operatore logico è traducibile nella logica enunciativa, se l'operatore è funzione di verità dei suoi costituenti. L'argomento 'se mangio, allora vivo, quindi vivo' richiede una premessa implicita ma è traducibile nella logica enunciativa, ergo ha un operatore logico come funzione di verità.",
    "Il tema di Ettore e quello di Alessandro sono pressoché identici. Evidentemente, uno dei due ha copiato.",
    "Dal momento che mi hai detto che ci saremmo incontrati al porto e tu non c'eri, sei un bugiardo, se non un idiota. Quindi non posso credere a nulla di quello che dici. Se sei un idiota, quello che dici è sbagliato e dunque sgradevole, inoltre se sei bugiardo allora sei pure una cattiva persona, e quindi anche sgradevole. Chi sta con i bugiardi non sta a proprio agio. Grazie a questo, non posso stare a mio agio. Se esiste qualcuno che sta a proprio agio con i bugiardi, allora non sono io.",
    "L'argomentazione precedente è infondata per due ragioni. Anzitutto, al porto io c'ero, ma evidentemente non mi hai visto, quindi una delle tue premesse è falsa. E poi il tuo ragionamento non è deduttivo.",
    "Le previsioni meteorologiche dicono che pioverà, il cielo appare molto minaccioso e la lancetta del barometro sta scendendo rapidamente. Pioverà e nel migliore dei casi annegheremo. Da questo segue che dobbiamo immediatamente chiedere soccorso.",
    "Mi ama e non mi ama. Allora mi ama.",
    "Tutte le scimitarre hanno una impugnatura. Questo oggetto ha una impugnatura. Questo oggetto è una scimitarra.",
    "Chiunque abbia una laurea in filosofia da Torino ha superato l'esame di logica. Coloro che lo hanno superato conoscono perfettamente la differenza tra uso e menzione. Alessio ha scritto: \"Leibniz si scrive senza la t\". Ergo Alessio non si è laureato in filosofia.",
    "Tutti i filosofi dell'antica Grecia sono ormai morti. Socrate è stato condannato a morte nell'antica Grecia. Dunque Socrate è un filosofo dell'antica Grecia.",
    "Tutti gli uomini sono mortali. Quindi Socrate è mortale, se è uno degli uomini.",
    "Se la logica enunciativa ha un algoritmo per decidere se una formula è derivabile da un insieme, allora è decidibile. La logica enunciativa classica è decidibile.",
    "Non riesco a concepire un mondo in cui l'acqua non sia potabile. Per questo, è necessario che l'acqua sia potabile.",
    "Non dovresti andare a correre. Infatti, hai male al ginocchio e se uscirai a correre il dolore potrà solamente peggiorare.",
    "Il vaccino Pfizer è sicuro, siccome ha superato la validazione dell’EMA e siccome tutti i vaccini validati dall’EMA sono sicuri.",
    "La strada era piena di gente che mangiava il gelato. Un cane correva senza guinzaglio. Due bambini giocavano a carte su una panchina.",
    "Al fondo di ogni credenza c'è una verità. Al fondo di ogni salone c'è una credenza. Dunque al fondo di ogni salone c'è una verità.",
    "Se Pino ha vinto la corsa campestre, allora Nino è arrivato secondo oppure Gino è arrivato terzo. Gino non è arrivato terzo. Quindi, se Nino non è arrivato secondo, allora Pino non ha vinto la corsa campestre.",
    "Se l'investimento dei capitali rimane costante, allora cresceranno le spese del governo oppure si verificheranno fenomeni di disoccupazione. Se non aumenteranno le spese di governo, potranno essere ridotte le tasse. Se le tasse potranno essere ridotte e l'investimento dei capitali rimane costante, non si avranno fenomeni di disoccupazione. Quindi aumenteranno le spese del governo.",
    "Settembre, Aprile e Novembre hanno 30 giorni. Aprile ha 30 giorni se e solo se Maggio non ha 30 giorni, e se Novembre ha 30 giorni allora anche Maggio ha 30 giorni. Dunque, Febbraio ha 40 giorni.",
    "I computer possono pensare se e solo se possono avere emozioni. Se i computer possono avere emozioni, allora possono anche avere desideri. Ma i computer non possono pensare se hanno desideri. Dunque, i computer non possono pensare.",
    "Se fa bel tempo andiamo a fare una passeggiata sul Montello. Se stiamo in casa giochiamo a Monopoli. O andiamo a fare una passeggiata sul Montello o stiamo in casa. Quindi, o fa bel tempo o giochiamo a Monopoli.",
    "Se Pino ha vinto la corsa campestre, allora, se Nino è arrivato secondo, allora Gino è arrivato terzo. Nino non è arrivato secondo. Quindi, o Pino ha vinto o Gino è arrivato terzo.",
    "Se Pino ha vinto la corsa campestre, allora Nino è arrivato secondo e Gino è arrivato terzo. Nino non è arrivato secondo. Quindi Pino non ha vinto la corsa campestre.",
    "Se sono innocente, mi presento davanti ai giudici. Ma mi presenterò davanti ai giudici. Dunque sono innocente.",
    "Se mi presento davanti ai giudici, sono colpevole. Ma non mi presenterò davanti ai giudici. Quindi non sono colpevole.",
    "Giovanni va a lavoro o gioca a tennis. Non è andato a lavoro. Dunque sta giocando a tennis.",
    "Se una persona è intelligente, è anche interessante. Se una persona si applica è ugualmente interessante. Marianna è molto intelligente ma non si applica. Quindi Marianna non è interessante.",
    "I cani sono affettuosi. Anche i gatti lo sono. Perciò non si può dire che non sia vero che i gatti e i cani sono affettuosi.",
    "Mi piace il gelato. Infatti, non è vero che, nonostante tutto, non mi piace il gelato.",
    "Ci sono dubbi sulla tua tesi. Dunque non si può dire che non ci siano dubbi su di essa.",
    "Se non sei convinto delle tue opzioni fermati a riflettere. Se sei convinto delle tue opzioni fai una scelta. Ma non sei convinto delle tue opzioni. Quindi ferma a riflettere e non compiere una scelta.", 
    "Se lui è bravo a surf allora io sono Napoleone.",
    "Oggi sarà impegnativo o rilassante. Oggi mi rilasserò.",
    "Miriam è simpatica. Quindi è anche intelligente.",
    "Luigi non pratica sport. Quindi non ha tanti amici.",
    "Se non vengo al cinema: ci sono solo due possibilità: o resto a casa oppure vado a mangiare una pizza qui sotto. Ma la pizza qui sotto non mi piac. Inoltre, in televisione non c'è niente di interessante. Quindi vengo al cinema",
    "Ciascun triangolo isoscele ha tutti i lati uguali. Tutti i triangoli hanno tre lati. Presa una cosa qualsiasi, se quella cosa è un triangolo, è un triangolo isoscele. Non possiamo quindi dubitare che ciascun trangolo ha tre lati uguali.",
    "Tra le cose che giovano alla salute ci sono: una dieta sana e l'abitudine al movimento fisico. Ciò che non giova alla salute, la danneggia. Dunque, ascoltare buona musica arreca danni alla salute."
  )

