name: Build Typst document
on: [push]
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses:  Jarivanbakel/typst-action@v3
        with:
          input_files: lista_es.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: lista_es.pdf
