name: Build Typst document

on:
  push:
    paths-ignore:
      - '**.pdf'

permissions:
  contents: write

jobs:
  build_typst:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Typst PDF
        uses: Jarivanbakel/typst-action@v3
        with:
          input_files: lista_es.typ

      - name: Move PDF to output location
        run: |
          mkdir -p pdf
          mv lista_es.pdf pdf/lista_es.pdf

      - name: Commit and push PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf/lista_es.pdf
          git commit -m "Add generated PDF [auto]" || echo "No changes to commit"
          git push
